version: '3'

volumes:

  wms-pg-data: {}
  wms-rabbitmq-data: {}

services:

  wms-postgres:
    image: sameersbn/postgresql:10-1
    restart: always
    command: postgres -c 'max_connections=2000'
    environment:
      DB_NAME: tallent
      DB_USER: postgres
      DB_PASS: totvs@123
      PG_PASSWORD: totvs@123
    ports:
      - 5432:5432
    volumes:
      - wms-pg-data:/var/lib/postgresql

  wms-pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: acistecnologia@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dev-vr
    ports:
      - 8082:80


      
